name: Terraform
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v5

      - name: setup the terraform
        uses: hashicorp/setup-terraform@v4

      - name: check the terraform version
        run: terraform version